name: Twitter Fast Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # حدثنا النسخة هنا عشان الـ TypeError يختفي

      - name: Install Dependencies
        run: |
          pip install pandas twikit

      - name: Run bot
        env:
          TW_USER: ${{ secrets.TW_USER }}
          TW_PASS: ${{ secrets.TW_PASS }}
          TW_EMAIL: ${{ secrets.TW_EMAIL }}
        run: python bot_script.py
