name: Twitter Browser Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas selenium webdriver-manager
          
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Run bot
        env:
          TW_USER: ${{ secrets.TW_USER }}
          TW_PASS: ${{ secrets.TW_PASS }}
          TW_EMAIL: ${{ secrets.TW_EMAIL }}
        run: python bot_script.py

      - name: Upload Debug Files
        if: always() # السطر ده بيخليه يرفع الصورة حتى لو البوت فشل
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            error_log.png
            page_source.html
