name: Twitter Browser Bot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Selenium & Chrome
        run: |
          pip install pandas selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run bot
        env:
          TW_USER: ${{ secrets.TW_USER }}
          TW_PASS: ${{ secrets.TW_PASS }}
          TW_EMAIL: ${{ secrets.TW_EMAIL }}
        run: python bot_script.py
